pub mod trait_demo;
pub mod string_demo;
mod hash_demo;
mod circle_ref_demo;
mod close_demo;
mod close2_demo;
mod close3_demo;
mod tree_demo;
mod trait2_demo;
mod state_demo;
mod unsafe_demo;
mod macro_demo;